import type { BuiltinCommandDefinition } from "@/shared/types";

export const BUILTIN_COMMANDS: BuiltinCommandDefinition[] = [
  {
    id: "fileTree",
    title: "文件树",
    category: "导航",
    surfaceSuggestion: ["dock-left-top"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "outline",
    title: "大纲",
    category: "导航",
    surfaceSuggestion: ["dock-left-top"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "bookmark",
    title: "书签",
    category: "面板",
    surfaceSuggestion: ["dock-left-bottom"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "tag",
    title: "标签",
    category: "面板",
    surfaceSuggestion: ["dock-right-top"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "inbox",
    title: "收集箱",
    category: "面板",
    surfaceSuggestion: ["dock-right-bottom"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "backlinks",
    title: "反向链接",
    category: "面板",
    surfaceSuggestion: ["dock-right-top"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "graphView",
    title: "文档关系图",
    category: "导航",
    surfaceSuggestion: ["dock-bottom-left"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "globalGraph",
    title: "全局关系图",
    category: "导航",
    surfaceSuggestion: ["dock-bottom-left"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "config",
    title: "设置",
    category: "系统",
    surfaceSuggestion: ["statusbar-right", "topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "globalSearch",
    title: "全局搜索",
    category: "搜索",
    surfaceSuggestion: ["topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "stickSearch",
    title: "钉住搜索",
    category: "搜索",
    surfaceSuggestion: ["topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "goBack",
    title: "后退",
    category: "导航",
    surfaceSuggestion: ["topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "goForward",
    title: "前进",
    category: "导航",
    surfaceSuggestion: ["topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "recentDocs",
    title: "最近文档",
    category: "导航",
    surfaceSuggestion: ["topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "mainMenu",
    title: "主菜单",
    category: "系统",
    surfaceSuggestion: ["statusbar-left"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "dailyNote",
    title: "今日日记",
    category: "系统",
    surfaceSuggestion: ["topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "newFile",
    title: "新建文档",
    category: "系统",
    surfaceSuggestion: ["topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "riffCard",
    title: "闪卡",
    category: "系统",
    surfaceSuggestion: ["statusbar-right"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "syncNow",
    title: "立即同步",
    category: "系统",
    surfaceSuggestion: ["statusbar-right"],
    requiresContext: false,
    stability: "stable",
  },
];
