import type { BuiltinCommandDefinition } from "@/shared/types";

export const BUILTIN_COMMANDS: BuiltinCommandDefinition[] = [
  {
    id: "backlinks",
    title: "反向链接",
    category: "面板",
    surfaceSuggestion: ["dock-right-top"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "config",
    title: "设置",
    category: "系统",
    surfaceSuggestion: ["statusbar-right", "topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "recentDocs",
    title: "最近文档",
    category: "导航",
    surfaceSuggestion: ["topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "dataHistory",
    title: "数据历史",
    category: "系统",
    surfaceSuggestion: ["dock-panel", "statusbar-right"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "dailyNote",
    title: "今日日记",
    category: "系统",
    surfaceSuggestion: ["topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "riffCard",
    title: "闪卡",
    category: "系统",
    surfaceSuggestion: ["statusbar-right"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "syncNow",
    title: "立即同步",
    category: "系统",
    surfaceSuggestion: ["statusbar-right"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "restartPlugins",
    title: "重启所有插件",
    category: "系统",
    surfaceSuggestion: ["statusbar-right"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "switchLeftDock",
    title: "左面板浮动切换",
    category: "面板",
    surfaceSuggestion: ["dock-left-top", "dock-left-bottom", "topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "switchRightDock",
    title: "右面板浮动切换",
    category: "面板",
    surfaceSuggestion: ["dock-right-top", "dock-right-bottom", "topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "switchBottomDock",
    title: "底栏浮动切换",
    category: "面板",
    surfaceSuggestion: ["dock-bottom-left", "dock-bottom-right", "statusbar-left", "statusbar-right"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "switchAllDock",
    title: "全部面板浮动切换",
    category: "面板",
    surfaceSuggestion: ["topbar", "statusbar-right"],
    requiresContext: false,
    stability: "stable",
  },
];
