import type { BuiltinCommandDefinition } from "@/shared/types";

export const BUILTIN_COMMANDS: BuiltinCommandDefinition[] = [
  {
    id: "backlinks",
    title: "反向链接",
    category: "面板",
    surfaceSuggestion: ["dock-right-top"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "config",
    title: "设置",
    category: "系统",
    surfaceSuggestion: ["statusbar-right", "topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "recentDocs",
    title: "最近文档",
    category: "导航",
    surfaceSuggestion: ["topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "dailyNote",
    title: "今日日记",
    category: "系统",
    surfaceSuggestion: ["topbar"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "riffCard",
    title: "闪卡",
    category: "系统",
    surfaceSuggestion: ["statusbar-right"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "syncNow",
    title: "立即同步",
    category: "系统",
    surfaceSuggestion: ["statusbar-right"],
    requiresContext: false,
    stability: "stable",
  },
  {
    id: "restartPlugins",
    title: "重启所有插件",
    category: "系统",
    surfaceSuggestion: ["statusbar-right"],
    requiresContext: false,
    stability: "stable",
  },
];
